builtin_interfaces/Time stamp
float32 usage_percent
float32 freq_current_mhz
float32 temperature_celsius    # -1.0 if unavailable
float32 load_avg_1m            # -1.0 if unavailable (Windows)
float32 load_avg_5m
float32 load_avg_15m
float64 iowait_seconds         # -1.0 if unavailable
float64 user_seconds
float64 system_seconds
float64 idle_seconds
int64 ctx_switches
int64 interrupts
int64 soft_interrupts
